### ISSUE TITLE
CARD TRADE not working

### ISSUE THREAD

**Issue by kAbAsTrEiT** [pokecrystal-mobile/pokecrystal-mobile-en#30]
Tested on two real GBC via infrared port the card trading and it still doesn't work, it doesn't save the cards in the card list, i.e. in the internal memory of the cartridges.

How to recreate:

In the MOBILE > CARD FOLDER menu, select 'MY CARD'.
input a phone number for yourself.

Then go back to the CARD FOLDER menu and add a card for a friend, and a phone number for them.
This should make the 'TRADE' option appear in the CARD FOLDER menu.
Do this on two cartridges, and use the 'TRADE' option to trade cards between gameboys.

**Comment by gb-mobile** [comment]
We ran a test where I set the PLAYER_NAME_LENGTH constant back to 6 (Japanese value) instead of 8, and the cards traded successfully, so the reason it's deleting the card upon trading via IR is because it's not sending all the data, and thus presumably the end is being cut off or something, We just can't figure out where the value is in the code that needs to be changed to accommodate the US value.

This is likely in engine\link\mystery_gift.asm

**Comment by gb-mobile** [comment]
Tested and working.
Thank you Damien!
